// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6CNp9dXP3SsvX4k6MF__fe6vIM__0_GQ',
    appId: '1:959142042243:web:d66a7f9f238c9c22ab99b6',
    messagingSenderId: '959142042243',
    projectId: 'musify-30',
    authDomain: 'musify-30.firebaseapp.com',
    storageBucket: 'musify-30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDScUuYFxupjsyQYafiGvJR5GbdfYgXOGw',
    appId: '1:959142042243:android:bee1cada47058dbdab99b6',
    messagingSenderId: '959142042243',
    projectId: 'musify-30',
    storageBucket: 'musify-30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuH4uc7N35GoKwFzRx8SLNG5K-QX5OeTA',
    appId: '1:959142042243:ios:b5ccb874c072888aab99b6',
    messagingSenderId: '959142042243',
    projectId: 'musify-30',
    storageBucket: 'musify-30.appspot.com',
    iosClientId: '959142042243-8mi5sctk61supbg2u2uqist7vqbu3rta.apps.googleusercontent.com',
    iosBundleId: 'com.nascon.musify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuH4uc7N35GoKwFzRx8SLNG5K-QX5OeTA',
    appId: '1:959142042243:ios:b5ccb874c072888aab99b6',
    messagingSenderId: '959142042243',
    projectId: 'musify-30',
    storageBucket: 'musify-30.appspot.com',
    iosClientId: '959142042243-8mi5sctk61supbg2u2uqist7vqbu3rta.apps.googleusercontent.com',
    iosBundleId: 'com.nascon.musify',
  );
}
